import numpy as np

A= np.array([4,16,3,9])
arp= A.reshape(2,2)
sq= np.sqrt(A)
print("square root=",sq)
sine=np.sin(A)
print("sine=",sine)
cosine=np.cos(A)
print("cos=",cosine)
tangent=np.tan(A)
print("tan=",tangent)
logarithm=np.log(A)
print("log=",logarithm)
exponent=np.exp(A)
print("exp=",exponent)
log_ten=np.log10(A)
print("log10=",log_ten)
log_two=np.log2(A)
print("log2=",log_two)